imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default        
        types:
            device_id:  MedicalDevices\Infrastructure\Persistence\Doctrine\Type\DoctrineDeviceId    
        connections:
            default:            
                driver:   pdo_sqlite
                path:     "%database_path%/case.db3"
   

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager:   default
        entity_managers:
            default:        
                auto_mapping: false
                connection:       default
                mappings:
                    dev_mapping:
                        type: xml
                        dir: "%kernel.root_dir%/../src/MedicalDevices/Infrastructure/Persistence/Doctrine/Mapping"
                        prefix: MedicalDevices\Domain
                        is_bundle: false
                        alias: med  
                hydrators:
                    DeviceHydrator: MedicalDevices\Infrastructure\Persistence\Doctrine\Hydrator\DeviceHydrator                

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: case
    document_managers:
        default:
            mappings:
                dev_mongo_mapping:
                    type: xml
                    dir: "%kernel.root_dir%/../src/MedicalDevices/Infrastructure/Persistence/DoctrineMongoDB/Mapping"
                    prefix: MedicalDevices\Domain
                    is_bundle: false
                    alias: med
            metadata_cache_driver: array # array, apc, xcache, memcache

jms_serializer:
    metadata:
        directories:
            APP:
                namespace_prefix: MedicalDevices\Application\DTO
                path: "%kernel.root_dir%/../src/AppBundle/Resources/config/serializer"

fos_rest:
    param_fetcher_listener: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
