services:
    # Framework services   
    serialized.param.converter:
        class: AppBundle\Request\SerializedParamConverter
        arguments: ["@serializer"] 
        tags:
            - { name: request.param_converter, priority: -40, converter: param_converter }  
    listener.publisher:
        class: AppBundle\Request\Publisher
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }         
