MedicalDevices\Application\DTO\Device\Identifier\DeviceIdentifierRequestDTO: 
    properties:
        type:
            type: string    
        value:
            type: string
        isReferenceIdentifier:
            type: boolean
