MedicalDevices\Application\DTO\Device\Identifier\DeviceRequestDTO: 
    properties:
        categoryId:
            type: string      
        model:
            type: MedicalDevices\Application\DTO\Device\Model\ModelRequestDTO
        deviceIdentifiers:
            type: ArrayCollection<MedicalDevices\Application\DTO\Device\Identifier\DeviceIdentifierRequestDTO>
            xml_map:
                entry_name: identifier
