parameters:
    med.devices.services.init: '%med.devices.services.params%'
        

services:
    # External services. Based on third party components    
    ext.services.serializer:
        class: MedicalDevicesBundle\ExternalServices\Serializer        
        arguments: ['@init']
    ext.services.validation.error.handler:
        class: MedicalDevicesBundle\ExternalServices\ValidationErrorHandler
        
    # Framawork services. Based on tool provided by Symfony framawork     
    init.factory:
        class: MedicalDevicesBundle\Framework\ConfigFactory
        arguments: ['@service_container']        
    init: 
        class: MedicalDevices\Configuration\Configuration
        factory: 'init.factory:createConfiguration'
    repository.collection.provider:
        class: MedicalDevicesBundle\Framework\RepositoryCollectionProvider
        arguments: ['@init', '@doctrine.orm.entity_manager']
